### ISSUE TITLE
Components: MainArticle

### ISSUE THREAD

**Issue by katerinabredihina** [KaterinaB10/Project-React#8]
To create MainArticle component that will be on the top of the Lending page.

**Comment by KaterinaB10** [comment]
![Uploading Skjermbilde 2024-03-27 142918.png…]()

**Comment by katerinabredihina** [comment]
<img width="329" alt="Skjermbilde 2024-03-27 142918" src="https://github.com/KaterinaB10/Project-React/assets/148851754/1a5e500c-faa3-4211-bc75-893061393140">
